### ISSUE TITLE
Peer review:

### ISSUE THREAD

**Issue by agonzalezrubiosaab1** [noahbrown29/WebTech-Term-Project-NB#2]
Peer review: Alejandra's feedback
Technical issues:
1. The list icon on the right corner does not open
2. There is no submit button in the form

content suggestions:
1. I would use more pages to separate the content
2. The pictures become too large, they could be more subtle

**Comment by noahbrown29** [comment]
I removed how large the pictures become and I am working on a submit button for the form! Thanks so much! :)
