### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by ylevy1** [noahbrown29/WebTech-Term-Project-NB#3]
Your website has a lot of content and I can tell you put a lot of work into it! To make it easier to navigate through the website, I would add a bar at the top with a way to get to the other companies once you have already clicked into one of them. Furthermore, the photos that enlarge when you hover over with your mouse are somewhat distracting to whats on the rest of the page. For example, on the site with the Boring Company, as I am reading the content, if I scroll onto a photo it moves the entire content of the page just to fit the new size of the picture. The user has to scroll down to see everything which might be inconvenient. Also, the form doesnt have a submit button for the user and the search icon on the top right is not working properly. Otherwise, great job!

**Comment by noahbrown29** [comment]
Hi! thanks so much for the suggestions. I changed the hover height and width so it is not so dramatic and distracting! Also, I added a submit button for the form!
