### ISSUE TITLE
Peer Review 

### ISSUE THREAD

**Issue by ajosephs1** [noahbrown29/WebTech-Term-Project-NB#4]
Hey Noah,
I really like the beginnings of your website and I'm sure with a few adjustments to the style it will look a lot better and be easy to navigate. Some suggestions I would make are to make sure that the content padding adjusts with the window size as I have to scroll at the bottom of the screen so see all the content. I like the navigation bar and I think the logos would look a bit better smaller especially with that dynamic added to it. I also think it would be helpful to hyperlink the "Companies of Elon Musk" on each page so it goes back to the homepage. Overall the content looks great and I like the images and different dynamics, I'm sure it will turn out great.

**Comment by noahbrown29** [comment]
Hi,
Thank you for your recommendations. I have changed the padding so it adjusts with the window and also changed the maximum height and width the picture hovers. I also hyperlinked the Title to the home page. Thanks for the suggestions!
